paths:
  raw_data: data/raw
  processed_data: data/processed
  interim_data:
    insights: data/interim/insights
    plotting: data/interim/plotting
  figures: reports/figures
files:
  raw_dataset: ai_education_usage_global
  processed_dataset: ai_education_usage_global_processed
  insights:
    tool_preference_year: AI Tool Preference by Year
    tool_preference_country: AI Tool Preference by Country
  plotting:
    ai_usage_yearly: Yearly AI Usage Summary
    structural_summary_country: Country wise Structural Summary
